"""baseline schema

Revision ID: 01f614faa2d0
Revises: 
Create Date: 2026-06-13 19:19:24.273689
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01f614faa2d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('SEMI', 'PORTEUR', 'FOURGON', 'TAUTLINER', name='camion_type_enum'), nullable=False),
    sa.Column('capacite_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_palettes', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIBLE', 'EN_MISSION', 'MAINTENANCE', 'PANNE', name='camion_status_enum'), nullable=False),
    sa.Column('consommation_base_l_100km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chauffeur_defaut_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # camions <-> chauffeurs is a mutual-FK cycle; the cross FK is added with
    # op.create_foreign_key after both tables exist (see end of upgrade()).
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('chauffeurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('permis_type', sa.Enum('B', 'C', 'CE', 'D', name='permis_type_enum'), nullable=False),
    sa.Column('permis_numero', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIF', 'CONGE', 'ARRET_MALADIE', 'INACTIF', name='chauffeur_status_enum'), nullable=False),
    sa.Column('camion_defaut_id', sa.Integer(), nullable=True),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # cross FK to camions added after both tables exist (see end of upgrade()).
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(
        'camions_chauffeur_defaut_id_fkey', 'camions', 'chauffeurs',
        ['chauffeur_defaut_id'], ['id'],
    )
    op.create_foreign_key(
        'chauffeurs_camion_defaut_id_fkey', 'chauffeurs', 'camions',
        ['camion_defaut_id'], ['id'],
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('fenetre_ouverture', sa.Time(), nullable=True),
    sa.Column('fenetre_fermeture', sa.Time(), nullable=True),
    sa.Column('exigences', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('import_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_id'), 'ingestion_logs', ['id'], unique=False)
    op.create_table('kpi_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('frequence', sa.Enum('daily', 'weekly', 'monthly', 'yearly', name='kpi_frequence_enum'), nullable=False),
    sa.Column('direction', sa.Enum('UP', 'DOWN', name='kpi_direction_enum'), nullable=False),
    sa.Column('target_2025', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('green_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('yellow_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('green_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('yellow_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plan_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.SmallInteger(), nullable=False),
    sa.Column('periode', sa.Enum('JOUR', 'SEMAINE', 'MOIS', name='periode_enum'), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut_plan', sa.Enum('DRAFT', 'EN_REVUE', 'VALIDE', 'EXECUTE', 'CLOTURE', name='statut_plan_enum'), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_validation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valide_par', sa.String(length=100), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('demandes_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('quantite_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nombre_palettes', sa.SmallInteger(), nullable=True),
    sa.Column('date_livraison', sa.Date(), nullable=False),
    sa.Column('heure_arrivee_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heure_arrivee_reelle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantite_livree_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('NOUVELLE', 'PLANIFIEE', 'EN_COURS', 'LIVREE', 'ANNULEE', name='statut_demande_enum'), nullable=False),
    sa.Column('priorite', sa.Enum('NORMALE', 'HAUTE', 'URGENTE', name='priorite_enum'), nullable=False),
    sa.Column('livree_a_temps', sa.Boolean(), nullable=True),
    sa.Column('source_import', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_journalier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_def_id', sa.Integer(), nullable=False),
    sa.Column('date_mesure', sa.Date(), nullable=False),
    sa.Column('plant', sa.String(length=50), nullable=True),
    sa.Column('valeur', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('qte_total_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('qte_livree_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('qte_a_temps_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_consomme_l', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('km_parcourus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('km_a_vide', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('nb_incidents', sa.Integer(), nullable=True),
    sa.Column('nb_missions', sa.Integer(), nullable=True),
    sa.Column('cout_total_eur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_calcul', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kpi_def_id'], ['kpi_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_def_id', 'date_mesure', 'plant')
    )
    op.create_table('kpi_mensuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_def_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.SmallInteger(), nullable=False),
    sa.Column('mois', sa.SmallInteger(), nullable=False),
    sa.Column('plant', sa.String(length=50), nullable=True),
    sa.Column('valeur', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.Enum('OK', 'WARN', 'ALERT', 'NA', name='kpi_status_enum'), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('date_calcul', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kpi_def_id'], ['kpi_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_def_id', 'annee', 'mois', 'plant')
    )
    op.create_table('plan_mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('camion_id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('date_mission', sa.Date(), nullable=False),
    sa.Column('heure_sortie_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heure_sortie_reelle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heure_retour_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heure_retour_reelle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('PLANIFIEE', 'EN_COURS', 'TERMINEE', 'ANNULEE', name='statut_mission_enum'), nullable=False),
    sa.Column('mode', sa.Enum('NORMAL', 'PREMIUM', name='mode_mission_enum'), nullable=False),
    sa.Column('km_parcourus', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('km_a_vide', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('charge_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('charge_palettes', sa.SmallInteger(), nullable=True),
    sa.Column('fuel_consomme_l', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cout_consommables_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cout_emballage_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cout_transport_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cout_premium_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('load_eff_kg_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('load_eff_pallets_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('load_eff_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['camion_id'], ['camions.id'], ),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason_category', sa.String(length=50), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_version.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenement_alea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_version_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('demande_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('PANNE_VEHICULE', 'RETARD_TRAFIC', 'CLIENT_INDISPONIBLE', 'DEPASSEMENT_CAPACITE', 'DEMANDE_LAST_MINUTE', 'CLIENT_COMPLAINT', name='evenement_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_evenement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('impact_delai_min', sa.Integer(), nullable=True),
    sa.Column('resolu', sa.Boolean(), nullable=True),
    sa.Column('date_resolution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_local.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['plan_mission.id'], ),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_demande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('ordre_livraison', sa.SmallInteger(), nullable=False),
    sa.Column('eta_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_reelle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('NOUVELLE', 'PLANIFIEE', 'EN_COURS', 'LIVREE', 'ANNULEE', name='statut_demande_enum'), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_local.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['plan_mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['plan_mission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livraison_preuve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_demande_id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('LIVREE', 'PARTIELLE', 'REFUSEE', name='pod_status_enum'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantite_livree_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('signataire', sa.String(length=120), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_local.id'], ),
    sa.ForeignKeyConstraint(['mission_demande_id'], ['mission_demande.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livraison_preuve_demande_id'), 'livraison_preuve', ['demande_id'], unique=False)
    op.create_index(op.f('ix_livraison_preuve_mission_demande_id'), 'livraison_preuve', ['mission_demande_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livraison_preuve_mission_demande_id'), table_name='livraison_preuve')
    op.drop_index(op.f('ix_livraison_preuve_demande_id'), table_name='livraison_preuve')
    op.drop_table('livraison_preuve')
    op.drop_table('notification_log')
    op.drop_table('mission_demande')
    op.drop_table('evenement_alea')
    op.drop_table('planning_change_log')
    op.drop_table('plan_mission')
    op.drop_table('kpi_mensuel')
    op.drop_table('kpi_journalier')
    op.drop_table('demandes_local')
    op.drop_table('users')
    op.drop_table('plan_version')
    op.drop_table('kpi_definition')
    op.drop_index(op.f('ix_ingestion_logs_id'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_table('clients')
    op.drop_table('chauffeurs')
    op.drop_table('camions')
    # ### end Alembic commands ###
